version: '3.3'
services:
  front:
    image: node:22
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 4200:4200
    command: sh -c "
      npm i -g @angular/cli &&
      ng serve --host 0.0.0.0"